services:
  db:
    image: postgres:16
    container_name: morpheus-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: morpheus
    ports:
      - "5432:5432"
    volumes:
      - morpheus_pg_data:/var/lib/postgresql/data

volumes:
  morpheus_pg_data: